### DISCUSSION TITLE
Can't get Device Triggers working

### DISCUSSION THREAD

**Discussion by caspre24** [unixorn/ha-mqtt-discoverable#301] [Q&A]
Hi there,
First of all: thanks for the nice library!
I can't seem to get the device trigger working. Everything else (I tested switch, binary sensor) is working perfectly fine. This is my code:
```python
    mqtt_settings = Settings.MQTT(
        host=args.hostname,
        port=args.port,
        username=args.user,
        password=args.password,
    )

    # Define the device. At least one of `identifiers` or `connections` must be supplied
    device_id = args.device_id or args.name
    device_info = DeviceInfo(name=args.name, identifiers=device_id)

    # Associate the sensor with the device via the `device` parameter
    btn_name = "Button"
    trigger_info = DeviceTriggerInfo(
        name=btn_name,
        type="button_press",
        subtype="action",
        unique_id="af0c7de6-f734-4df7-9469-94071a68b02d",
        device=device_info,
    )
    # Instantiate the device trigger
    button_trigger = DeviceTrigger(Settings(mqtt=mqtt_settings, entity=trigger_info))
    button_trigger.trigger("action")
```
This is what is shown under "MQTT INFO" on the device page in HomeAssistant:
![image](https://github.com/user-attachments/assets/23cf62fe-2edd-4196-8250-d4594f629663)

- There is no indication that any trigger events are received by HomeAssistant.
- It also doesn't list any subscribed topics like it would do for sensors or switches.
- I checked the mqtt topics manually with a separate client and I can see the trigger events being posted correctly, but HomeAssistant doesn't seem to pick them up or something is missing to let HomeAssistant know where to look :thinking: 

Am I missing something? Any help is much appreciated :pray:

**Comment by kratz00** [comment]
What do you want to trigger via your device?

On the `Device info` page you can add an `Automation` which is triggered via your device and define some action (basically you define what should happen when the your device triggers).

![Screenshot_2025-03-11_21-06-11](https://github.com/user-attachments/assets/2d379a74-1c69-4723-a7b7-fd831a9685b1)

Here is an YAML example, how it could look like [(source):](https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#via-mqtt-device-trigger-recommended)

```
automation:
    - alias: Respond to button click
      triggers:
          - trigger: device
            domain: mqtt
            device_id: ad44cabee4c646f493814306aa6446e1
            type: action
            subtype: arrow_left_click
      actions:
          - action: light.toggle
            target:
                entity_id: light.bedroom
```
